# Generated by Django 4.2.4 on 2023-08-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.CharField()),
                ('name', models.CharField()),
                ('url', models.CharField()),
                ('next_end_date', models.DateField()),
            ],
        ),
    ]
