# Generated by Django 4.2.4 on 2023-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_app', '0003_race_race_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(),
        ),
    ]
