# Generated by Django 4.2.4 on 2023-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_app', '0004_alter_race_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='url',
            field=models.URLField(),
        ),
    ]
