
# Generated by Django 4.2.4 on 2023-08-10 19:46


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3100)]),
        ),
    ]
